enable_disqus: false
enable_analytics: false
highlighter: rouge
permalink: pretty

#_url: http://localhost:4000
#_url: https://flaviomicheletti.github.io/linux
_url: http://www.devfuria.com.br/linux

secao: linux

defaults:
  -
    scope:
      path: ""
    values:
      layout: "artigo"
